fix(back) rename variable added creation of fake variable and function to add user to masterclasss_groupe + logging with alembic
Hetic-web3-g1/PROJET_FIL_ROUGE_W3_G4 pull request #52
Opened 2023-07-11 11:16 UTC by domino659

2023-07-11 12:11 UTC, jeremie-j commented on backend/src/entities/masterclasses/models.py
>      Column("id", Integer, primary_key=True, unique=True, nullable=False),
on a vraiment besoin d'un index sur cette table ?

2023-07-11 12:12 UTC, jeremie-j commented on backend/src/entities/masterclasses/models.py
>      Column("id", Integer, primary_key=True, unique=True, nullable=False),
oui bon je sais ça fait pas parti des modfis de la pr mdrr

2023-07-11 12:33 UTC, jeremie-j requested changes

2023-07-11 12:33 UTC, jeremie-j commented on backend/src/entities/users/models.py
> +    Column("secondary_role", ARRAY(String()), nullable=True),
Nope du coup si tu veux récuperer les `secondary_role` (avec un 's' aussi dud coup ?) du user, faut faire une jointure avec la table `masterclass_user`
pourquoi pas avoir une table

```
# masterclass_user
INT id,
UUID user_id, foreign key 'user.id'
UUID masterclass_id, fk 'masterclasss.id'
```
et 
```
# user_masterclass_role
INT masterclass_user_id, fg masterclass_user.id
STRING role
```
avec plusieurs ligne si le user a plusieurs masterlcasses roles 

pour recuperer le tout 
```sql
SELECT *, array_agg(user_masterclass_role.role) as roles FROM user_masterclass_role JOIN masterclass_user ON masterclass_user.id = user_masterclass_role.masterclass_user_id GROUP BY masterclass_user.id
```

2023-07-11 13:00 UTC, domino659 commented on backend/src/entities/masterclasses/models.py
>      Column("id", Integer, primary_key=True, unique=True, nullable=False),
bah ca coute rien osef

2023-07-13 11:21 UTC, jeremie-j approved these changes

2023-07-13 11:23 UTC, merged